"""empty message

Revision ID: 1b8cc1d3deaa
Revises: 69f8d3669af7
Create Date: 2019-12-11 09:44:30.184571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8cc1d3deaa'
down_revision = '69f8d3669af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('article', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'title')
    op.drop_column('article', 'description')
    # ### end Alembic commands ###
