"""empty message

Revision ID: 3871dde37f08
Revises: 1b8cc1d3deaa
Create Date: 2019-12-11 09:53:55.342119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3871dde37f08'
down_revision = '1b8cc1d3deaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('slug', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'article', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='unique')
    op.drop_column('article', 'slug')
    # ### end Alembic commands ###
