"""empty message

Revision ID: 75d148214081
Revises: 3871dde37f08
Create Date: 2019-12-31 09:39:15.649245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d148214081'
down_revision = '3871dde37f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('youtube_id', sa.Text(), server_default='https://www.youtube.com/embed/nZq_jeYsbTs', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'youtube_id')
    # ### end Alembic commands ###
