"""empty message

Revision ID: f6b0bf8c9d0d
Revises: 5a0ec28c5114
Create Date: 2020-01-07 13:58:56.014651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b0bf8c9d0d'
down_revision = '5a0ec28c5114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favoritor_assoc_favoriter_fkey', 'favoritor_assoc', type_='foreignkey')
    op.create_foreign_key(None, 'favoritor_assoc', 'userprofile', ['favoriter'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoritor_assoc', type_='foreignkey')
    op.create_foreign_key('favoritor_assoc_favoriter_fkey', 'favoritor_assoc', 'users', ['favoriter'], ['id'])
    # ### end Alembic commands ###
